typography_spectrum: 0.4078858974389732
color:
  brandStrength: 0.39614966977387667
  lightness: 0.6729456814937294
  saturation: 0.27335465513169765
  rhythmicContrast: 0.6125719624105841
  brandColors:
    - '#2F2933'
    - '#01A2A6'
    - '#29D9C2'
    - '#BDF271'
    - '#FFFFA6'
layout_spectrum: 0.985934681026265
author:
  name: Malane Shani
  email: malaneshani@gmail.com
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/92e82317-316e-4fe0-90ca-f616695c747e.jpg
name: Malane Shani
navigation:
  - id: f156a3af-d63f-43a5-8399-a9dc21721421
    url: 2016-07-22-about-malane.html
    name: About Malane
    type: content
  - id: 71081fa7-4750-479b-adfc-32e69699b587
    url: >-
      2016-07-22-malane-shanis-conversations-with-goddess-m-on-high-frequenc.html
    name: Events
    type: content
  - id: 781f3177-4295-461b-a387-38d86bc8b437
    url: >-
      2016-07-22-this-experience-was-great-i-must-say-i-really-enjoyed-the-d.html
    name: Testimonials
    type: content
title: ''
