typography_spectrum: 0.9748101658187807
color:
  brandStrength: 0.04240634269081056
  lightness: 0.8154669958166778
  saturation: 0.7591657121665776
  rhythmicContrast: 0.7939179665409029
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
layout_spectrum: 0.9409808765631169
author:
  name: Malane Shani
  email: malaneshani@gmail.com
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/92e82317-316e-4fe0-90ca-f616695c747e.jpg
name: Malane Shani
navigation:
  - id: f156a3af-d63f-43a5-8399-a9dc21721421
    url: 2016-07-22-about-malane.html
    name: About Malane
    type: content
  - id: 71081fa7-4750-479b-adfc-32e69699b587
    url: >-
      2016-07-22-malane-shanis-conversations-with-goddess-m-on-high-frequenc.html
    name: Events
    type: content
title: ''
